<?php
/*
 * Impmentation of hook_migrate_api()
 */

function migrate_elx_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'elx' => array(
        'title' => t('ELX Migrations'),
      ),
    ),
    'migrations' => array(
      'ProductDetail' => array(
        'class_name' => 'ProductdetailMigration',
        'group_name' => 'elx',
      ),
      'List' => array(
        'class_name' => 'ListMigration',
        'group_name' => 'elx',
      ),
    	'ListitemParagraph' => array(
    		'class_name' => 'ListitemParagraphMigration',
    		'group_name' => 'elx',
    	),
    	'Hotspot' => array(
    		'class_name' => 'HotspotMigration',
    		'group_name' => 'elx',
    	),
    	'HotspotitemParagraph' => array(
    		'class_name' => 'HotspotitemParagraphMigration',
    		'group_name' => 'elx',
    	),
    	'Contentobject' => array(
    				'class_name' => 'ContentobjectMigration',
    				'group_name' => 'elx',
    	),
    ),
  );
  return $api;
}

function migrate_elx_form_alter(&$form, &$form_state, $form_id){
	if($form_id == 'feeds_import_form' && (arg(1) == 'product_details' || arg(1) == 'data_xls') ){
		//dpm($form);
		$form['feeds']['elx_assets'] = array(
			'#type' => 'plupload',
			'#title' => t('Upload Assets'),
			'#weight'=> -1,
      '#plupload_settings' => array(
        'max_file_size' => '268435456b',
      ),
		);
        //unset($form['#submit']);
		$form['#submit'][] = 'migrate_elx_files_submit';
	}
}

function migrate_elx_feeds_presave(FeedsSource $source, $entity, $item) {
  if ($source->id =='learning_points') {
    // Skip saving this entity.
    $entity->feeds_item->skip = TRUE;
  }
}

function migrate_elx_files_submit($form, &$form_state) {
	$saved_files = array(); //Array to capture file objects
	$scheme = variable_get('file_default_scheme', 'public') . '://';
	$directoryname = 'elx_bulk/assets'; // Directory where images are collected
	$imagebankpath = $scheme . $directoryname;
	file_prepare_directory($imagebankpath, FILE_CREATE_DIRECTORY); // Create the folder if it doesn't exist
	// We can't use file_save_upload() because of
	// http://www.jacobsingh.name/content/tight-coupling-no-not
	// file_uri_to_object();
	foreach ($form_state['values']['feeds']['elx_assets'] as $uploaded_file) {
		if ($uploaded_file['status'] == 'done') {
			$source = $uploaded_file['tmppath'];
			$destination = file_stream_wrapper_uri_normalize($imagebankpath .'/'. $uploaded_file['name']);
			// Rename it to its original name, and put it in its final home.
			// Note - not using file_move here because if we call file_get_mime
			// (in file_uri_to_object) while it has a .tmp extension, it horks.
			$destination = file_unmanaged_move($source, $destination, FILE_EXISTS_REPLACE);
			$file = plupload_file_uri_to_object($destination);
      $existing_files = file_load_multiple(array(), array('uri' => $destination));
      if (!empty($existing_files)) {
        $existing = reset($existing_files);
        $file->fid = $existing->fid;
      }
			file_save($file);
			$saved_files[] = $file;
		}
		else {
			form_set_error('elx_assets', "Upload of {$uploaded_file['name']} failed");
		}
	}



  //migrate_static_registration(array('Contentobject'));
  //$migration = Migration::getInstance('Contentobject');
  //$result = $migration->processImport(array('force'=>TRUE));
  //dpm($result);
}

function migrate_elx_menu(){

  $items['admin/content/bulk-upload'] = array(
    'title' => 'Wysiwyg Tool',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_elx_upload_form'),
    'description' => 'Configure client-side editors.',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  return $items;
}

function migrate_elx_upload_form($form, &$form_state){

  $form['upload'] = array(
    '#type' => 'fieldset',
    '#title' => t('Bulk Upload Content'),
    '#collapsible' => FALSE,
  );
  /*$form['upload']['type'] = array(
    '#type' => 'select',
    '#options' => array(
      'learning_content' => t('Learning Content'),
      'product' => t('Product Details'),
      'story' => t('Stories'),
    ),
    '#description' => t('Please choose what kind of content will be uploaded'),
  );*/
  $form['upload']['assets'] = array(
  '#type' => 'plupload',
  '#title' => t('Upload Assets'),
);
  $form['upload']['file'] = array(
    '#type' => 'file',
    '#title' => t('csv File'),
    //"#upload_validators"  => array("file_validate_extensions" => array("zip")),

  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'upload',

  );

  return $form;
}

/**
 * Implements hook_field_attach_presave().
 */
function migrate_elx_field_attach_presave($entity_type, $entity) {
  // Determine the list of instances to iterate on.
  list(, , $bundle) = entity_extract_ids($entity_type, $entity);
  $instances = field_info_instances($entity_type, $bundle);
  foreach ($instances as $instance) {
    $field_name = $instance['field_name'];
    $field = field_info_field($field_name);
    if ($field['type'] == 'image' && !empty($entity->{$field_name})) {
      $fids = array();
      $languages = field_available_languages($entity_type, $field);
      foreach ($languages as $langcode) {
        $items = isset($entity->{$field_name}[$langcode]) ? $entity->{$field_name}[$langcode] : array();
        foreach ($items as $item) {
          if (!empty($item['fid'])) {
            $fids[] = $item['fid'];
          }
        }
      }
      $files = file_load_multiple($fids);
      foreach ($files as $file) {
        if ($instance['widget']['type'] == 'image_image') {
          // Create preview image.
          $style = image_style_load($instance['widget']['settings']['preview_image_style']);
          drupal_register_shutdown_function('_migrate_elx_image_derivative', $style, $file->uri);
        }
        foreach ($instance['display'] as $display) {
          if ($display['type'] == 'image') {
            // Create display image.
            $style = image_style_load($display['settings']['image_style']);
            drupal_register_shutdown_function('_migrate_elx_image_derivative', $style, $file->uri);
          }
        }
      }
    }
  }
}

/**
 * Make sure derivative image exists.
 */
function _migrate_elx_image_derivative($style, $image_uri) {
  $derivative_uri = image_style_path($style['name'], $image_uri);
  // Don't start generating the image if the derivative already exists
  // or if generation is in progress in another thread.
  $lock_name = 'image_style_deliver:' . $style['name'] . ':' . drupal_hash_base64($image_uri);
  $lock_acquired = lock_acquire($lock_name);
  if ($lock_acquired) {
    if (!file_exists($derivative_uri)) {
      image_style_create_derivative($style, $image_uri, $derivative_uri);
    }
    lock_release($lock_name);
  }
}
