<?php


/**
 * Implements hook_token_info().
 */
function account_password_token_token_info() {
  $info['tokens']['user']['account-password'] = array(
    'name' => t('User Account password'),
    'description' => t('Provides user account password token.'),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function account_password_token_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  if (isset($data['user']) && isset($data['user']->pass)) {
    $replacements['[user:account-password]'] = aes_get_password($data['user']->uid, $decrypt = TRUE);
  }

  return $replacements;
}


