<?php
/**
 * Created by PhpStorm.
 * User: Adrienne Cabouet
 * Creates a Guest URL for each ELX User account using:
 * -node->title,
 * -field_door,
 * -field_country,
 * -field_region_list,
 * -field_market_name.
 * One URL for each door.
 *
 */

/**
 * Implements hook_node_presave().
 */
function elx_guest_urls_node_presave($node)
{
    $node_wrapper = entity_metadata_wrapper('node', $node);

    if($node_wrapper->getBundle() == 'guest_accounts'){
        //Clear out any existing guest URLs
        $node_wrapper->field_guest_url->set(NULL);

        //Create an empty array to store for each guest URL to be generated
        $URLs = array();
        $completed_urls = array();

        //Get account name, country, region list, and market name fields in vars
        $acct = preg_replace('/\s+/', '', $node_wrapper->label()); //this removes whitespace from node->title
        $account_name = 'account=' . $acct;
        $country = 'country=' . $node_wrapper->field_country->value();
        $region = 'region=' . $node_wrapper->field_region_list->value();
        $market = 'market=' . $node_wrapper->field_market_name->value();

        //Get doors (there may be multiple)
        $doors = $node_wrapper->field_door->value();

        //Loop through doors and create URL param array for each
        if (is_array($doors)) {
            foreach ($doors as $door) {
                $door_value = 'door=' . $door;
                $url_array = array(
                    $account_name,
                    $door_value,
                    $country,
                    $region,
                    $market
                );
                array_push($URLs, $url_array);
            }
        }

        foreach ($URLs as $url) {
            //Example URL: http://myelx.com/#/signup?account=Acmexx&door=4&market=X&country=Y&region=Z
            $guest_url_value = 'http://myelx.com/#/signup?'; //TBD
            //$guest_url_value = 'http://stagemyelxrp.cloudapp.net/#/signup?';

            //Concatenate
            $amp_separated = implode('&', $url);

            //Add to guest URL stub
            $guest_url_value .= $amp_separated;

            array_push($completed_urls, $guest_url_value);

        }

        //Save each generated guest url in it's own key in field_guest_url
        $node_wrapper->field_guest_url = $completed_urls;
    }
}




